trainer:
  devices: [0]
  max_epochs: 30
  log_every_n_steps: 100
  precision: '32-true'
  gradient_clip_val: 1.0
  # val_check_interval: 0.5
  # accumulate_grad_batches: 4

model:
  lr: 1e-4
  weight_decay: 0.01 # default
  in_channels: 8 # (3 rgb + 1 depth) * 2 frames
  pct_start: 0.3 # default
  div_factor: 25 # default
  cycle_momentum: True # default
  beta: 1.0 # 160 according to https://arxiv.org/pdf/2107.13263
  zeta: 15 # according to https://arxiv.org/pdf/2107.13263

dataset:
  ds_type: "simcol"
  batch_size: 64
  num_workers: 8
  size: 518

  # SimCol3D: splits as per https://github.com/ESandML/SimCol-Entry/blob/main/train.py
  data_dir: './datasets/SyntheticColon/'
  train_list: './datasets/SyntheticColon/train.txt'
  val_list: './datasets/SyntheticColon/val.txt'
  test_list: './datasets/SyntheticColon/test.txt'


hydra:
  run:
    dir: configs/experiments/pose_estimation/${dataset.ds_type}/l${model.lr}_b${dataset.batch_size}_e${trainer.max_epochs}